# Generated by Django 6.0.1 on 2026-03-31 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbergame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
